tedious/Stash

- src/Stash/Item.php
The default is supposed to be PRECOMPUTE but due to an error the old default was put back into place.
> Fixed default invalidation method

- .travis.yml
- tests/travis/php_setup.sh
This is added in allowing failures (although it currently passes), as php7 is stlll pre-alpha.
> Added php 7 testing to travis-ci

- src/Stash/Item.php
This code can never be reached because of an earlier return when the
invalidation is `Invalidation::NONE`.
see https://github.com/Jimdo/Stash/blob/6ca8bcc2e2dd9a85ce7a225057ca1ea97e333fe1/src/Stash/Item.php#L500-L504
> Remove obsolete case / dead code.

- src/Stash/Driver/FileSystem.php
When using stash with several PHP processes, it happens that though the `if(is_dir())`-statement did not yet see a directory, it exists when you come to the `mkdir()`-statement.
I suppose we could also get rid of the `is_dir()` call completely if `mkdir()` is comparable cheap with already created dir’s (haven’t tested that, yet)
> prevent mkdir from throwing warnings

- src/Stash/Interfaces/ItemInterface.php
- src/Stash/Item.php
- src/Stash/Pool.php
- tests/Stash/Test/AbstractItemTest.php
With heavy use of Stash creation of Item classes & setKey shows up
in profile data, so the change tries to reduce function calls in these.
Suggested followup is executeGet().
Note: Might need another pass on this tomorrow for CS / tests if this is otherwise accepted.
Note2: Contains interface change on Item to force array type on $key, felt like a easy way to avoid having to check.
> Reduce function calls in creation of Item classes

- src/Stash/Driver/AbstractDriver.php
- src/Stash/Driver/Apc.php
- src/Stash/Driver/BlackHole.php
- src/Stash/Driver/Composite.php
- src/Stash/Driver/Ephemeral.php
- src/Stash/Driver/FileSystem.php
- src/Stash/Driver/Memcache.php
- src/Stash/Driver/Redis.php
- src/Stash/Driver/Sqlite.php
- tests/Stash/Test/Driver/AbstractDriverTest.php
- tests/Stash/Test/Driver/ApcTest.php
- tests/Stash/Test/Stubs/DriverCallCheckStub.php
- tests/Stash/Test/Stubs/DriverExceptionStub.php
- tests/Stash/Test/Stubs/DriverUnavailableStub.php
* Fixes that the File and Sqlite drivers were not usable out of the box without calling setOptions() first.
* Fixes that __destruct() is not defined on the interface and does not need to be defined if it's simply a no-op empty function.
This resolves Issue #230 and maintains backwards compatibility.
> Added an AbstractDriver class for shared driver functionality.

- .php_cs
- composer.json
This PR
:bulb: Note that I required the package using
```
$ composer require --dev --sort-packages fabpot/php-cs-fixer:^1.9
```
resulting in packages being nicely sorted and properly indented.
> Enhancement: Require fabpot/php-cs-fixer:^1.9

- src/Stash/Pool.php
- tests/Stash/Test/AbstractPoolTest.php
With this patch we can access to Item by key:
```php
$pool = new Stash\Pool();
$result = $pool->getItemIterator(array('TEST1', 'TEST2'));
echo $result['TEST2']->get();
```
> using cache keys as ArrayIterator keys

- src/Stash/Item.php
In case when cache is empty and two (or more) clients asks cached data we got abnormal situation: first client locks cache, and other got isHit = true but we have no old value and data is null.
For ex.
```
<?php
class Something {
public function getObject($key) {
$item = $pool->getItem($key);
$data = $item->get(Invalidation::OLD);
if ($item->isMiss()) {
$item->lock(5);
// long query from DB
$data = ORM::getByKey($key);
$item->set($data, 3600);
}
return $data;
}
// ....some times later we call this method...
public function someFunc() {
return $this->getObject('my-key')
->getSomeField(); // for non first clients this will trigger fatal error because $data is null
}
}
```
> do not set isHit if data is empty on Invalidation::OLD

- CHANGELOG.md
- src/Stash/Exception/WindowsPathMaxLengthException.php
- src/Stash/Interfaces/ItemInterface.php
- src/Stash/Interfaces/PoolInterface.php
- src/Stash/Item.php
- src/Stash/Pool.php
- src/Stash/Session.php
- tests/Stash/Test/AbstractItemTest.php
- tests/Stash/Test/AbstractPoolTest.php
- tests/Stash/Test/CacheExceptionTest.php
- tests/Stash/Test/Driver/EphemeralTest.php
- tests/Stash/Test/Driver/FileSystemTest.php
- tests/Stash/Test/Driver/MemcacheAnyTest.php
- tests/Stash/Test/Driver/MemcacheTest.php
- tests/Stash/Test/Driver/SqliteAnyTest.php
- tests/Stash/Test/ItemLoggerTest.php
- tests/Stash/Test/PoolNamespaceTest.php
- tests/Stash/Test/Stubs/PoolGetDriverStub.php
The goal behind this branch is to bring Stash current with PSR6 as it currently stands. These changes are mostly cosmetic API changes but sometimes stretch further than that. This will *not* be a backwards compatible branch.
> Bring Stash current with PSR6 for v1

- src/Stash/Driver/AbstractDriver.php
Error always throw `Stash\Driver\AbstractDriver is not available` insead of point what dirver not allowed.
> Fix non informative exception text

- CHANGELOG.md
- src/Stash/Driver/FileSystem.php
> Remove call to Utilities::getBaseDirectory unless path option is not passed

- .coveralls.yml
The coveralls configuration has changed, resulting in an exception being thrown and updated line counts not being sent. This update fixes that.
> Update coveralls configuration

- src/Stash/Pool.php
Incorrect case of namespace will cause some issues with autoloading and case-sensitive file systems
> Incorrect case of namespace

- src/Stash/Driver/Sqlite.php
because base directory method always wants to create a folder only call this function if needed. on secured systems, the temp folder may not be writeable.
> only add base directory if path is not present

- src/Stash/Driver/Sub/Memcached.php
Adds support for `Memcached::OPT_REMOVE_FAILED_SERVERS`.
> Added support for the 'remove_failed_servers' option of the memcached extension

- .travis.yml
- tests/Stash/Test/Driver/RedisTest.php
Add missing `@expectedException` to `testBadDisconnect()` test so expected warning raised by Redis::connect() wont break test.
Also added `sudo: required` to `.travis.yml` because it is not set by default on new repos, so forked repos like mine won't fail to build now.
> Fix Travis-CI redis tests

- src/Stash/Item.php
When `$time`  is not `\DateTime` but implements `\DateTimeInterface` it is ignored and `self::$cacheTime` is used.
> Allow DateTimeInterface in `executeSet`

- src/Stash/Driver/Composite.php
This pull request fixes a test suite issue when running with upcoming PHP 7.2.
```
$ git clone https://github.com/tedious/Stash.git
Cloning into 'Stash'...
remote: Counting objects: 4811, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4811 (delta 2), reused 1 (delta 1), pack-reused 4806
Receiving objects: 100% (4811/4811), 885.59 KiB | 1.34 MiB/s, done.
Resolving deltas: 100% (2797/2797), done.
Checking connectivity... done.
$ cd Stash/
$ git log -1
commit 7ea9749784152dcd2dab72c4bbf2bef18c326e41
Merge: 69313c9 5b7414b
Author: Robert Hafner <tedivm@tedivm.com>
Date:   Sun Apr 23 10:16:57 2017 -0700
Merge pull request #353 from tedious/hotfix/composer-warnings
Use friendsofphp not fabpot php-cs-fixer
$ composer install
Loading composer repositories with package …
```
> [Driver/Composite] Fix PHP 7.2 failure

- src/Stash/Driver/Apc.php
As described in #365, Stash can currently run into a fatal error in specific circumstances.
This PR introduces a check in `Apc->isAvailable()` to let the driver fail early if APCu is not configured to run in CLI environments.
> Apc Driver: Check for 'apc.enable_cli' in cli calls

- src/Stash/Driver/Ephemeral.php
- tests/Stash/Test/Driver/EphemeralTest.php
This makes it possible for the ephemeral driver to use bounded amounts of memory.
It is useful if you want to "cache the cache" in an Ephemeral/Other composite stack, but limit memory consumption, or if you want to use the Ephemeral driver directly in scenarios where the number of unique Items is occasionally very large.
> Add option to limit number of items stored in ephemeral driver.

- src/Stash/Driver/FileSystem/NativeEncoder.php
We recently ran into some trouble because of the slightly obscure and still unfixed T_ENCAPSED_AND_WHITESPACE bug in PHP. It has to do with string parts looking like variables.
First of all, the `include()` should be protected by a try/catch block. This works in PHP 7 and PHP 5 will just ignore the catch block. 
Second, arrays and resources don’t need `serialize()`, they can be enoded with `var_export()` which returns native PHP code. Obviously, this will decode faster and is not prone to the forementioned bug.
> Mitigate T_ENCAPSED_AND_WHITESPACE bug

- composer.json
- tests/Stash/Test/AbstractItemTest.php
- tests/Stash/Test/Driver/AbstractDriverTest.php
- tests/Stash/Test/Driver/BlackHoleTest.php
- tests/Stash/Test/Driver/MemcacheAnyTest.php
- tests/Stash/Test/Driver/MemcacheTest.php
- tests/Stash/Test/Driver/RedisArrayTest.php
- tests/Stash/Test/Driver/RedisSocketTest.php
- tests/Stash/Test/Driver/RedisTest.php
- tests/Stash/Test/Driver/SqliteAnyTest.php
- tests/Stash/Test/Driver/SqlitePdoSqlite3Test.php
- tests/Stash/Test/SessionTest.php
Composer won't install anything on a PHP 8 environment due to version contraints coming with PhpUnit 6. This PR is a moderate test upgrade.
- PhpUnit 8.0 requires PHP 7.2+
- Needed to update Test method return types such as `public function setUp : void`
N.B. Running PhpUnit will output deprecation warnings on certain test methods, such as `assertAttributeEquals` and `getObjectAttribute`. Tests should work anyhow (though can't tell for sophistaicated cache techniques like Redis, haven't got them)
> Modernize PhpUnit

- src/Stash/Driver/FileSystem.php
- tests/Stash/Test/Driver/FileSystemTest.php
I was using Stash as the cache backend for Doctrine, and, being nosy replaced the key hash function with a transparent function (`fn($data) => $data`) and noticed that the names of the files are not completely finished
which was a bit alarming because this can cause unintentional cache conflicts or poisoning*
After digging around I found 
https://github.com/tedious/Stash/blob/1a9c7557f928ffa00168fe607725d6cb4e4763da/src/Stash/Driver/FileSystem.php#L292-L298
the `$i == $this->directorySplit` was supposed to prevent this, however this will always be false, thus I have now replaced it with a bit more robust way of splitting that should prevent this.
and which now works correctly as shown here
*: So this can actually open to cache poisoning attacks, but since the default uses md5 which has an …
> Filesystem Driver: Fix dir split not finishing cleanly

- src/Stash/Driver/Redis.php
> update redis delete function

- src/Stash/Item.php
ItemInterface has the invalidationMethod property as @param int
Item has the invalidationMethod property as @param string ... which causes static analysis tools like phpstan to complain.
This PR just changes the phpdoc comment in Item.php to match the interface's.
> phpdoc fix (Item::$invalidationMethod)

- src/Stash/Utilities.php
- tests/Stash/Test/UtilitiesTest.php
Fix for encoding numeric values in strings.
Current behaviour is saving the value `"1"` into the `FileSystem` cache will detect it as numeric and actually store the integer `1`. This updates that behaviour to return the original string.
> Encoding Numeric Strings

- src/Stash/Driver/Sub/SqlitePdo.php
- tests/Stash/Test/Driver/SqlitePdoSqlite3Test.php
> work around SQLite PDO’s inability to enforce permissions for data files

- src/Stash/Driver/Redis.php
This PR implements an additional option `username` to be used with Redis clusters that have ACL rules (Redis 6+) with non-default users.
I have changed the `auth` method parameters to use associative arrays, because I thought it would be less confusing to someone reading the code. More info on parameter styles [here](https://github.com/phpredis/phpredis#auth).
How I tested it:
- Start a Redis container without authentication enabled.
- Try to connect and get something, without setting `username` or `password`.
- Result: "cache miss" (OK).
- Try to connect and get something, setting only the `password` option.
- Result:`Fatal error: Uncaught RedisException: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in …
> Add 'username' auth option to Redis driver

- src/Stash/Driver/Sub/Memcached.php
Use 0.17.5 version with php 8.1 and get such error:
```
Deprecated: Memcached::get(): Passing null to parameter #3 ($get_flags) of type int is deprecated in /app/www/vendor/tedivm/stash/src/Stash/Driver/Sub/Memcached.php on line 190
```
> Fix deprecation error on php 8.1

- .github/workflows/pr_tests.yml
- composer.json
- src/Stash/Exception/ItemKeyMissingException.php
- src/Stash/Interfaces/ItemInterface.php
- src/Stash/Interfaces/PoolInterface.php
- src/Stash/Item.php
- src/Stash/Pool.php
- tests/Stash/Test/AbstractItemTest.php
- tests/Stash/Test/AbstractItemTestCase.php
- tests/Stash/Test/AbstractPoolTestCase.php
- tests/Stash/Test/AbstractTestCase.php
- tests/Stash/Test/Driver/AbstractDriverTestCase.php
- tests/Stash/Test/Driver/ApcTest.php
- tests/Stash/Test/Driver/CompositeTest.php
- tests/Stash/Test/Driver/EphemeralTest.php
- tests/Stash/Test/Driver/FileSystemTest.php
- tests/Stash/Test/Driver/MemcacheTest.php
- tests/Stash/Test/Driver/RedisTest.php
- tests/Stash/Test/Driver/SqlitePdoSqlite3Test.php
- tests/Stash/Test/ItemLoggerTestCase.php
- tests/Stash/Test/ItemTest.php
- tests/Stash/Test/PoolNamespaceTest.php
- tests/Stash/Test/PoolTest.php
- tests/Stash/Test/Stubs/LoggerStub.php
- tests/Stash/Test/Stubs/PoolGetDriverStub.php
This PR updates the codebase to support `psr/cache` 3.0 and 2.0 (2.0 because 3.0 has narrower types). It makes a couple slight changes to the interfaces and implementations, probably most notable is that `item::set` will now throw an exception rather than return `false` if it's called when the item has no key set.
Resolves #420
> Update to psr/cache 3.0

- src/Stash/Interfaces/ItemInterface.php
- src/Stash/Interfaces/PoolInterface.php
- src/Stash/Item.php
- src/Stash/Pool.php
- src/Stash/Utilities.php
- tests/Stash/Test/Driver/AbstractDriverTestCase.php
- tests/Stash/Test/Stubs/PoolGetDriverStub.php
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated
> More explicit nullable types for PHP 8.4

- src/Stash/Utilities.php
Implicitly marking parameter $driver as nullable is deprecated, the explicit nullable type must be used instead
> Use explicit nullable type for PHP 8.4

- tests/Stash/Test/Driver/RedisTest.php
RedisTest errors with : 
```
1) Stash\Test\Driver\RedisTest::testBadDisconnect
PHPUnit\Framework\Exception: Class "Warning" does not exist
Caused by
ReflectionException: Class "Warning" does not exist
```
Fix by changing class to be RedisException which does seem to be thrown.
> RedisTest throws \RedisException, so expect that, not Warning

- src/Stash/Driver/Sub/Memcache.php
…not provide null. One option is perhaps MEMCACHE_COMPRESSED
> Fix memcache::set default argument from the deprecated null to false
